//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRDsubmit.AIRD.Service {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/", ConfigurationName="AIRD.Service.StatisticsReportingSoap")]
    public interface StatisticsReportingSoap {
        
        // CODEGEN: Generating message contract since message AddRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://FVST.Dyreforsoeg.ReportingWebService/Add", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AIRDsubmit.AIRD.Service.AddResponse Add(AIRDsubmit.AIRD.Service.AddRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FVST.Dyreforsoeg.ReportingWebService/Add", ReplyAction="*")]
        System.Threading.Tasks.Task<AIRDsubmit.AIRD.Service.AddResponse> AddAsync(AIRDsubmit.AIRD.Service.AddRequest request);
        
        // CODEGEN: Generating message contract since message FinalizeRequest has headers
        [System.ServiceModel.OperationContractAttribute(Action="http://FVST.Dyreforsoeg.ReportingWebService/Finalize", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        AIRDsubmit.AIRD.Service.FinalizeResponse Finalize(AIRDsubmit.AIRD.Service.FinalizeRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://FVST.Dyreforsoeg.ReportingWebService/Finalize", ReplyAction="*")]
        System.Threading.Tasks.Task<AIRDsubmit.AIRD.Service.FinalizeResponse> FinalizeAsync(AIRDsubmit.AIRD.Service.FinalizeRequest request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public partial class AuthInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string userNameField;
        
        private string passwordField;
        
        private System.Xml.XmlAttribute[] anyAttrField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string UserName {
            get {
                return this.userNameField;
            }
            set {
                this.userNameField = value;
                this.RaisePropertyChanged("UserName");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("Password");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAnyAttributeAttribute()]
        public System.Xml.XmlAttribute[] AnyAttr {
            get {
                return this.anyAttrField;
            }
            set {
                this.anyAttrField = value;
                this.RaisePropertyChanged("AnyAttr");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public partial class YearlyReportingInfoReponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private YearlyReportingInfo yearlyReportingInfoField;
        
        private ErrorMessage errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public YearlyReportingInfo YearlyReportingInfo {
            get {
                return this.yearlyReportingInfoField;
            }
            set {
                this.yearlyReportingInfoField = value;
                this.RaisePropertyChanged("YearlyReportingInfo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorMessage ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public partial class YearlyReportingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid approvalUnitIdField;
        
        private string captiaIdField;
        
        private int yearField;
        
        private bool isDoneField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid ApprovalUnitId {
            get {
                return this.approvalUnitIdField;
            }
            set {
                this.approvalUnitIdField = value;
                this.RaisePropertyChanged("ApprovalUnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string CaptiaId {
            get {
                return this.captiaIdField;
            }
            set {
                this.captiaIdField = value;
                this.RaisePropertyChanged("CaptiaId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public int Year {
            get {
                return this.yearField;
            }
            set {
                this.yearField = value;
                this.RaisePropertyChanged("Year");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public bool IsDone {
            get {
                return this.isDoneField;
            }
            set {
                this.isDoneField = value;
                this.RaisePropertyChanged("IsDone");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public partial class ErrorMessage : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codeField;
        
        private string messageField;
        
        private bool isSuccessField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int Code {
            get {
                return this.codeField;
            }
            set {
                this.codeField = value;
                this.RaisePropertyChanged("Code");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("Message");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public bool IsSuccess {
            get {
                return this.isSuccessField;
            }
            set {
                this.isSuccessField = value;
                this.RaisePropertyChanged("IsSuccess");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public partial class ReportingInfoResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private ReportingInfo reportingField;
        
        private ErrorMessage errorMessageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public ReportingInfo Reporting {
            get {
                return this.reportingField;
            }
            set {
                this.reportingField = value;
                this.RaisePropertyChanged("Reporting");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public ErrorMessage ErrorMessage {
            get {
                return this.errorMessageField;
            }
            set {
                this.errorMessageField = value;
                this.RaisePropertyChanged("ErrorMessage");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public partial class ReportingInfo : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string[] approvalReportingCaptiaIdLinksField;
        
        private ApprovalUnitReportingLink[] approvalUnitReportingLinksField;
        
        private string speciesOtherField;
        
        private int noOfAnimalsField;
        
        private string purposeOtherField;
        
        private string testingByLegislationOtherField;
        
        private string customSeverityField;
        
        private string comments1Field;
        
        private string comments2Field;
        
        private bool reuseField;
        
        private PlaceOfBirth placeOfBirthField;
        
        private bool creationOfNewGLField;
        
        private Purpose purposeField;
        
        private LegislativeRequirements legislativeRequirementsField;
        
        private Severity severityField;
        
        private GeneticStatus geneticStatusField;
        
        private Specie speciesField;
        
        private int reportingYearField;
        
        private System.Nullable<NHPSource> nHPSourceField;
        
        private System.Nullable<NHPGeneration> nHPGenerationField;
        
        private System.Nullable<TestingByLegislation> testingByLegislationField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=0)]
        public string[] ApprovalReportingCaptiaIdLinks {
            get {
                return this.approvalReportingCaptiaIdLinksField;
            }
            set {
                this.approvalReportingCaptiaIdLinksField = value;
                this.RaisePropertyChanged("ApprovalReportingCaptiaIdLinks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=1)]
        public ApprovalUnitReportingLink[] ApprovalUnitReportingLinks {
            get {
                return this.approvalUnitReportingLinksField;
            }
            set {
                this.approvalUnitReportingLinksField = value;
                this.RaisePropertyChanged("ApprovalUnitReportingLinks");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string SpeciesOther {
            get {
                return this.speciesOtherField;
            }
            set {
                this.speciesOtherField = value;
                this.RaisePropertyChanged("SpeciesOther");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public int NoOfAnimals {
            get {
                return this.noOfAnimalsField;
            }
            set {
                this.noOfAnimalsField = value;
                this.RaisePropertyChanged("NoOfAnimals");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PurposeOther {
            get {
                return this.purposeOtherField;
            }
            set {
                this.purposeOtherField = value;
                this.RaisePropertyChanged("PurposeOther");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public string TestingByLegislationOther {
            get {
                return this.testingByLegislationOtherField;
            }
            set {
                this.testingByLegislationOtherField = value;
                this.RaisePropertyChanged("TestingByLegislationOther");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string CustomSeverity {
            get {
                return this.customSeverityField;
            }
            set {
                this.customSeverityField = value;
                this.RaisePropertyChanged("CustomSeverity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string Comments1 {
            get {
                return this.comments1Field;
            }
            set {
                this.comments1Field = value;
                this.RaisePropertyChanged("Comments1");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=8)]
        public string Comments2 {
            get {
                return this.comments2Field;
            }
            set {
                this.comments2Field = value;
                this.RaisePropertyChanged("Comments2");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=9)]
        public bool Reuse {
            get {
                return this.reuseField;
            }
            set {
                this.reuseField = value;
                this.RaisePropertyChanged("Reuse");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=10)]
        public PlaceOfBirth PlaceOfBirth {
            get {
                return this.placeOfBirthField;
            }
            set {
                this.placeOfBirthField = value;
                this.RaisePropertyChanged("PlaceOfBirth");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=11)]
        public bool CreationOfNewGL {
            get {
                return this.creationOfNewGLField;
            }
            set {
                this.creationOfNewGLField = value;
                this.RaisePropertyChanged("CreationOfNewGL");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=12)]
        public Purpose Purpose {
            get {
                return this.purposeField;
            }
            set {
                this.purposeField = value;
                this.RaisePropertyChanged("Purpose");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=13)]
        public LegislativeRequirements LegislativeRequirements {
            get {
                return this.legislativeRequirementsField;
            }
            set {
                this.legislativeRequirementsField = value;
                this.RaisePropertyChanged("LegislativeRequirements");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=14)]
        public Severity Severity {
            get {
                return this.severityField;
            }
            set {
                this.severityField = value;
                this.RaisePropertyChanged("Severity");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=15)]
        public GeneticStatus GeneticStatus {
            get {
                return this.geneticStatusField;
            }
            set {
                this.geneticStatusField = value;
                this.RaisePropertyChanged("GeneticStatus");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=16)]
        public Specie Species {
            get {
                return this.speciesField;
            }
            set {
                this.speciesField = value;
                this.RaisePropertyChanged("Species");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=17)]
        public int ReportingYear {
            get {
                return this.reportingYearField;
            }
            set {
                this.reportingYearField = value;
                this.RaisePropertyChanged("ReportingYear");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=18)]
        public System.Nullable<NHPSource> NHPSource {
            get {
                return this.nHPSourceField;
            }
            set {
                this.nHPSourceField = value;
                this.RaisePropertyChanged("NHPSource");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=19)]
        public System.Nullable<NHPGeneration> NHPGeneration {
            get {
                return this.nHPGenerationField;
            }
            set {
                this.nHPGenerationField = value;
                this.RaisePropertyChanged("NHPGeneration");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true, Order=20)]
        public System.Nullable<TestingByLegislation> TestingByLegislation {
            get {
                return this.testingByLegislationField;
            }
            set {
                this.testingByLegislationField = value;
                this.RaisePropertyChanged("TestingByLegislation");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public partial class ApprovalUnitReportingLink : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid idField;
        
        private System.Guid approvalUnitIdField;
        
        private System.Guid reportingIdField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.Guid Id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("Id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.Guid ApprovalUnitId {
            get {
                return this.approvalUnitIdField;
            }
            set {
                this.approvalUnitIdField = value;
                this.RaisePropertyChanged("ApprovalUnitId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public System.Guid ReportingId {
            get {
                return this.reportingIdField;
            }
            set {
                this.reportingIdField = value;
                this.RaisePropertyChanged("ReportingId");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public enum PlaceOfBirth {
        
        /// <remarks/>
        O1,
        
        /// <remarks/>
        O2,
        
        /// <remarks/>
        O3,
        
        /// <remarks/>
        O4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public enum Purpose {
        
        /// <remarks/>
        PB1,
        
        /// <remarks/>
        PB2,
        
        /// <remarks/>
        PB3,
        
        /// <remarks/>
        PB4,
        
        /// <remarks/>
        PB5,
        
        /// <remarks/>
        PB6,
        
        /// <remarks/>
        PB7,
        
        /// <remarks/>
        PB8,
        
        /// <remarks/>
        PB9,
        
        /// <remarks/>
        PB10,
        
        /// <remarks/>
        PB11,
        
        /// <remarks/>
        PB12,
        
        /// <remarks/>
        PB13,
        
        /// <remarks/>
        PT21,
        
        /// <remarks/>
        PT22,
        
        /// <remarks/>
        PT23,
        
        /// <remarks/>
        PT24,
        
        /// <remarks/>
        PT25,
        
        /// <remarks/>
        PT26,
        
        /// <remarks/>
        PT27,
        
        /// <remarks/>
        PT28,
        
        /// <remarks/>
        PT29,
        
        /// <remarks/>
        PT30,
        
        /// <remarks/>
        PT31,
        
        /// <remarks/>
        PT32,
        
        /// <remarks/>
        PT33,
        
        /// <remarks/>
        PT34,
        
        /// <remarks/>
        PT35,
        
        /// <remarks/>
        PT36,
        
        /// <remarks/>
        PT37,
        
        /// <remarks/>
        PE40,
        
        /// <remarks/>
        PS41,
        
        /// <remarks/>
        PE42,
        
        /// <remarks/>
        PF43,
        
        /// <remarks/>
        PG43,
        
        /// <remarks/>
        PR51,
        
        /// <remarks/>
        PR52,
        
        /// <remarks/>
        PR53,
        
        /// <remarks/>
        PR61,
        
        /// <remarks/>
        PR62,
        
        /// <remarks/>
        PR63,
        
        /// <remarks/>
        PR64,
        
        /// <remarks/>
        PR71,
        
        /// <remarks/>
        PR81,
        
        /// <remarks/>
        PR82,
        
        /// <remarks/>
        PR83,
        
        /// <remarks/>
        PR84,
        
        /// <remarks/>
        PR85,
        
        /// <remarks/>
        PR86,
        
        /// <remarks/>
        PR87,
        
        /// <remarks/>
        PR88,
        
        /// <remarks/>
        PR89,
        
        /// <remarks/>
        PR90,
        
        /// <remarks/>
        PR91,
        
        /// <remarks/>
        PR92,
        
        /// <remarks/>
        PR93,
        
        /// <remarks/>
        PR94,
        
        /// <remarks/>
        PR95,
        
        /// <remarks/>
        PR96,
        
        /// <remarks/>
        PR97,
        
        /// <remarks/>
        PR98,
        
        /// <remarks/>
        PR99,
        
        /// <remarks/>
        PR100,
        
        /// <remarks/>
        PR101,
        
        /// <remarks/>
        PR102,
        
        /// <remarks/>
        PR103,
        
        /// <remarks/>
        PR104,
        
        /// <remarks/>
        PR105,
        
        /// <remarks/>
        PR106,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public enum LegislativeRequirements {
        
        /// <remarks/>
        LO1,
        
        /// <remarks/>
        LO2,
        
        /// <remarks/>
        LO3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public enum Severity {
        
        /// <remarks/>
        SV1,
        
        /// <remarks/>
        SV2,
        
        /// <remarks/>
        SV3,
        
        /// <remarks/>
        SV4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public enum GeneticStatus {
        
        /// <remarks/>
        GS1,
        
        /// <remarks/>
        GS2,
        
        /// <remarks/>
        GS3,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public enum Specie {
        
        /// <remarks/>
        A1,
        
        /// <remarks/>
        A2,
        
        /// <remarks/>
        A3,
        
        /// <remarks/>
        A4,
        
        /// <remarks/>
        A5,
        
        /// <remarks/>
        A6,
        
        /// <remarks/>
        A7,
        
        /// <remarks/>
        A8,
        
        /// <remarks/>
        A9,
        
        /// <remarks/>
        A10,
        
        /// <remarks/>
        A11,
        
        /// <remarks/>
        A12,
        
        /// <remarks/>
        A13,
        
        /// <remarks/>
        A14,
        
        /// <remarks/>
        A15,
        
        /// <remarks/>
        A16,
        
        /// <remarks/>
        A17,
        
        /// <remarks/>
        A18,
        
        /// <remarks/>
        A19,
        
        /// <remarks/>
        A20,
        
        /// <remarks/>
        A21,
        
        /// <remarks/>
        A22,
        
        /// <remarks/>
        A23,
        
        /// <remarks/>
        A24,
        
        /// <remarks/>
        A25,
        
        /// <remarks/>
        A26,
        
        /// <remarks/>
        A27,
        
        /// <remarks/>
        A28,
        
        /// <remarks/>
        A29,
        
        /// <remarks/>
        A30,
        
        /// <remarks/>
        A31,
        
        /// <remarks/>
        A32,
        
        /// <remarks/>
        A33,
        
        /// <remarks/>
        A34,
        
        /// <remarks/>
        A35,
        
        /// <remarks/>
        A36,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public enum NHPSource {
        
        /// <remarks/>
        NHPO1,
        
        /// <remarks/>
        NHPO2,
        
        /// <remarks/>
        NHPO3,
        
        /// <remarks/>
        NHPO4,
        
        /// <remarks/>
        NHPO5,
        
        /// <remarks/>
        NHPO6,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public enum NHPGeneration {
        
        /// <remarks/>
        NHPG1,
        
        /// <remarks/>
        NHPG2,
        
        /// <remarks/>
        NHPG3,
        
        /// <remarks/>
        NHPG4,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.1055.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
    public enum TestingByLegislation {
        
        /// <remarks/>
        LT1,
        
        /// <remarks/>
        LT2,
        
        /// <remarks/>
        LT3,
        
        /// <remarks/>
        LT4,
        
        /// <remarks/>
        LT5,
        
        /// <remarks/>
        LT6,
        
        /// <remarks/>
        LT7,
        
        /// <remarks/>
        LT8,
        
        /// <remarks/>
        LT9,
        
        /// <remarks/>
        LT10,
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Add", WrapperNamespace="http://FVST.Dyreforsoeg.ReportingWebService/", IsWrapped=true)]
    public partial class AddRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
        public AIRDsubmit.AIRD.Service.AuthInfo AuthInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/", Order=0)]
        public AIRDsubmit.AIRD.Service.ReportingInfo reportingInfo;
        
        public AddRequest() {
        }
        
        public AddRequest(AIRDsubmit.AIRD.Service.AuthInfo AuthInfo, AIRDsubmit.AIRD.Service.ReportingInfo reportingInfo) {
            this.AuthInfo = AuthInfo;
            this.reportingInfo = reportingInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="AddResponse", WrapperNamespace="http://FVST.Dyreforsoeg.ReportingWebService/", IsWrapped=true)]
    public partial class AddResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/", Order=0)]
        public AIRDsubmit.AIRD.Service.ReportingInfoResponse AddResult;
        
        public AddResponse() {
        }
        
        public AddResponse(AIRDsubmit.AIRD.Service.ReportingInfoResponse AddResult) {
            this.AddResult = AddResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Finalize", WrapperNamespace="http://FVST.Dyreforsoeg.ReportingWebService/", IsWrapped=true)]
    public partial class FinalizeRequest {
        
        [System.ServiceModel.MessageHeaderAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
        public AIRDsubmit.AIRD.Service.AuthInfo AuthInfo;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/", Order=0)]
        public AIRDsubmit.AIRD.Service.YearlyReportingInfo yearlyReportingInfo;
        
        public FinalizeRequest() {
        }
        
        public FinalizeRequest(AIRDsubmit.AIRD.Service.AuthInfo AuthInfo, AIRDsubmit.AIRD.Service.YearlyReportingInfo yearlyReportingInfo) {
            this.AuthInfo = AuthInfo;
            this.yearlyReportingInfo = yearlyReportingInfo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="FinalizeResponse", WrapperNamespace="http://FVST.Dyreforsoeg.ReportingWebService/", IsWrapped=true)]
    public partial class FinalizeResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/", Order=0)]
        public AIRDsubmit.AIRD.Service.YearlyReportingInfoReponse FinalizeResult;
        
        public FinalizeResponse() {
        }
        
        public FinalizeResponse(AIRDsubmit.AIRD.Service.YearlyReportingInfoReponse FinalizeResult) {
            this.FinalizeResult = FinalizeResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface StatisticsReportingSoapChannel : AIRDsubmit.AIRD.Service.StatisticsReportingSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class StatisticsReportingSoapClient : System.ServiceModel.ClientBase<AIRDsubmit.AIRD.Service.StatisticsReportingSoap>, AIRDsubmit.AIRD.Service.StatisticsReportingSoap {
        
        public StatisticsReportingSoapClient() {
        }
        
        public StatisticsReportingSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public StatisticsReportingSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsReportingSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public StatisticsReportingSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AIRDsubmit.AIRD.Service.AddResponse AIRDsubmit.AIRD.Service.StatisticsReportingSoap.Add(AIRDsubmit.AIRD.Service.AddRequest request) {
            return base.Channel.Add(request);
        }
        
        public AIRDsubmit.AIRD.Service.ReportingInfoResponse Add(AIRDsubmit.AIRD.Service.AuthInfo AuthInfo, AIRDsubmit.AIRD.Service.ReportingInfo reportingInfo) {
            AIRDsubmit.AIRD.Service.AddRequest inValue = new AIRDsubmit.AIRD.Service.AddRequest();
            inValue.AuthInfo = AuthInfo;
            inValue.reportingInfo = reportingInfo;
            AIRDsubmit.AIRD.Service.AddResponse retVal = ((AIRDsubmit.AIRD.Service.StatisticsReportingSoap)(this)).Add(inValue);
            return retVal.AddResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AIRDsubmit.AIRD.Service.AddResponse> AIRDsubmit.AIRD.Service.StatisticsReportingSoap.AddAsync(AIRDsubmit.AIRD.Service.AddRequest request) {
            return base.Channel.AddAsync(request);
        }
        
        public System.Threading.Tasks.Task<AIRDsubmit.AIRD.Service.AddResponse> AddAsync(AIRDsubmit.AIRD.Service.AuthInfo AuthInfo, AIRDsubmit.AIRD.Service.ReportingInfo reportingInfo) {
            AIRDsubmit.AIRD.Service.AddRequest inValue = new AIRDsubmit.AIRD.Service.AddRequest();
            inValue.AuthInfo = AuthInfo;
            inValue.reportingInfo = reportingInfo;
            return ((AIRDsubmit.AIRD.Service.StatisticsReportingSoap)(this)).AddAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        AIRDsubmit.AIRD.Service.FinalizeResponse AIRDsubmit.AIRD.Service.StatisticsReportingSoap.Finalize(AIRDsubmit.AIRD.Service.FinalizeRequest request) {
            return base.Channel.Finalize(request);
        }
        
        public AIRDsubmit.AIRD.Service.YearlyReportingInfoReponse Finalize(AIRDsubmit.AIRD.Service.AuthInfo AuthInfo, AIRDsubmit.AIRD.Service.YearlyReportingInfo yearlyReportingInfo) {
            AIRDsubmit.AIRD.Service.FinalizeRequest inValue = new AIRDsubmit.AIRD.Service.FinalizeRequest();
            inValue.AuthInfo = AuthInfo;
            inValue.yearlyReportingInfo = yearlyReportingInfo;
            AIRDsubmit.AIRD.Service.FinalizeResponse retVal = ((AIRDsubmit.AIRD.Service.StatisticsReportingSoap)(this)).Finalize(inValue);
            return retVal.FinalizeResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<AIRDsubmit.AIRD.Service.FinalizeResponse> AIRDsubmit.AIRD.Service.StatisticsReportingSoap.FinalizeAsync(AIRDsubmit.AIRD.Service.FinalizeRequest request) {
            return base.Channel.FinalizeAsync(request);
        }
        
        public System.Threading.Tasks.Task<AIRDsubmit.AIRD.Service.FinalizeResponse> FinalizeAsync(AIRDsubmit.AIRD.Service.AuthInfo AuthInfo, AIRDsubmit.AIRD.Service.YearlyReportingInfo yearlyReportingInfo) {
            AIRDsubmit.AIRD.Service.FinalizeRequest inValue = new AIRDsubmit.AIRD.Service.FinalizeRequest();
            inValue.AuthInfo = AuthInfo;
            inValue.yearlyReportingInfo = yearlyReportingInfo;
            return ((AIRDsubmit.AIRD.Service.StatisticsReportingSoap)(this)).FinalizeAsync(inValue);
        }
    }
}
