//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Web.Services.WebServiceBindingAttribute(Name="StatisticsReportingSoap", Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public interface IStatisticsReportingSoap {
    
    
    AuthInfo AuthInfoValue {
        get;
        set;
    }
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthInfoValue")]
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FVST.Dyreforsoeg.ReportingWebService/Add", RequestNamespace="http://FVST.Dyreforsoeg.ReportingWebService/", ResponseNamespace="http://FVST.Dyreforsoeg.ReportingWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    ReportingInfoResponse Add(ReportingInfo reportingInfo);
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapHeaderAttribute("AuthInfoValue")]
    [System.Web.Services.WebMethodAttribute()]
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://FVST.Dyreforsoeg.ReportingWebService/Finalize", RequestNamespace="http://FVST.Dyreforsoeg.ReportingWebService/", ResponseNamespace="http://FVST.Dyreforsoeg.ReportingWebService/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    YearlyReportingInfoReponse Finalize(YearlyReportingInfo yearlyReportingInfo);
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
[System.Xml.Serialization.XmlRootAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/", IsNullable=false)]
public partial class AuthInfo : System.Web.Services.Protocols.SoapHeader {
    
    private string userNameField;
    
    private string passwordField;
    
    private System.Xml.XmlAttribute[] anyAttrField;
    
    /// <remarks/>
    public string UserName {
        get {
            return this.userNameField;
        }
        set {
            this.userNameField = value;
        }
    }
    
    /// <remarks/>
    public string Password {
        get {
            return this.passwordField;
        }
        set {
            this.passwordField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlAnyAttributeAttribute()]
    public System.Xml.XmlAttribute[] AnyAttr {
        get {
            return this.anyAttrField;
        }
        set {
            this.anyAttrField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public partial class YearlyReportingInfoReponse {
    
    private YearlyReportingInfo yearlyReportingInfoField;
    
    private ErrorMessage errorMessageField;
    
    /// <remarks/>
    public YearlyReportingInfo YearlyReportingInfo {
        get {
            return this.yearlyReportingInfoField;
        }
        set {
            this.yearlyReportingInfoField = value;
        }
    }
    
    /// <remarks/>
    public ErrorMessage ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public partial class YearlyReportingInfo {
    
    private System.Guid approvalUnitIdField;
    
    private string captiaIdField;
    
    private int yearField;
    
    private bool isDoneField;
    
    /// <remarks/>
    public System.Guid ApprovalUnitId {
        get {
            return this.approvalUnitIdField;
        }
        set {
            this.approvalUnitIdField = value;
        }
    }
    
    /// <remarks/>
    public string CaptiaId {
        get {
            return this.captiaIdField;
        }
        set {
            this.captiaIdField = value;
        }
    }
    
    /// <remarks/>
    public int Year {
        get {
            return this.yearField;
        }
        set {
            this.yearField = value;
        }
    }
    
    /// <remarks/>
    public bool IsDone {
        get {
            return this.isDoneField;
        }
        set {
            this.isDoneField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public partial class ErrorMessage {
    
    private int codeField;
    
    private string messageField;
    
    private bool isSuccessField;
    
    /// <remarks/>
    public int Code {
        get {
            return this.codeField;
        }
        set {
            this.codeField = value;
        }
    }
    
    /// <remarks/>
    public string Message {
        get {
            return this.messageField;
        }
        set {
            this.messageField = value;
        }
    }
    
    /// <remarks/>
    public bool IsSuccess {
        get {
            return this.isSuccessField;
        }
        set {
            this.isSuccessField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public partial class ReportingInfoResponse {
    
    private ReportingInfo reportingField;
    
    private ErrorMessage errorMessageField;
    
    /// <remarks/>
    public ReportingInfo Reporting {
        get {
            return this.reportingField;
        }
        set {
            this.reportingField = value;
        }
    }
    
    /// <remarks/>
    public ErrorMessage ErrorMessage {
        get {
            return this.errorMessageField;
        }
        set {
            this.errorMessageField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public partial class ReportingInfo {
    
    private string[] approvalReportingCaptiaIdLinksField;
    
    private ApprovalUnitReportingLink[] approvalUnitReportingLinksField;
    
    private string speciesOtherField;
    
    private int noOfAnimalsField;
    
    private string purposeOtherField;
    
    private string testingByLegislationOtherField;
    
    private string customSeverityField;
    
    private string comments1Field;
    
    private string comments2Field;
    
    private bool reuseField;
    
    private PlaceOfBirth placeOfBirthField;
    
    private bool creationOfNewGLField;
    
    private Purpose purposeField;
    
    private LegislativeRequirements legislativeRequirementsField;
    
    private Severity severityField;
    
    private GeneticStatus geneticStatusField;
    
    private Specie speciesField;
    
    private int reportingYearField;
    
    private System.Nullable<NHPSource> nHPSourceField;
    
    private System.Nullable<NHPGeneration> nHPGenerationField;
    
    private System.Nullable<TestingByLegislation> testingByLegislationField;
    
    /// <remarks/>
    public string[] ApprovalReportingCaptiaIdLinks {
        get {
            return this.approvalReportingCaptiaIdLinksField;
        }
        set {
            this.approvalReportingCaptiaIdLinksField = value;
        }
    }
    
    /// <remarks/>
    public ApprovalUnitReportingLink[] ApprovalUnitReportingLinks {
        get {
            return this.approvalUnitReportingLinksField;
        }
        set {
            this.approvalUnitReportingLinksField = value;
        }
    }
    
    /// <remarks/>
    public string SpeciesOther {
        get {
            return this.speciesOtherField;
        }
        set {
            this.speciesOtherField = value;
        }
    }
    
    /// <remarks/>
    public int NoOfAnimals {
        get {
            return this.noOfAnimalsField;
        }
        set {
            this.noOfAnimalsField = value;
        }
    }
    
    /// <remarks/>
    public string PurposeOther {
        get {
            return this.purposeOtherField;
        }
        set {
            this.purposeOtherField = value;
        }
    }
    
    /// <remarks/>
    public string TestingByLegislationOther {
        get {
            return this.testingByLegislationOtherField;
        }
        set {
            this.testingByLegislationOtherField = value;
        }
    }
    
    /// <remarks/>
    public string CustomSeverity {
        get {
            return this.customSeverityField;
        }
        set {
            this.customSeverityField = value;
        }
    }
    
    /// <remarks/>
    public string Comments1 {
        get {
            return this.comments1Field;
        }
        set {
            this.comments1Field = value;
        }
    }
    
    /// <remarks/>
    public string Comments2 {
        get {
            return this.comments2Field;
        }
        set {
            this.comments2Field = value;
        }
    }
    
    /// <remarks/>
    public bool Reuse {
        get {
            return this.reuseField;
        }
        set {
            this.reuseField = value;
        }
    }
    
    /// <remarks/>
    public PlaceOfBirth PlaceOfBirth {
        get {
            return this.placeOfBirthField;
        }
        set {
            this.placeOfBirthField = value;
        }
    }
    
    /// <remarks/>
    public bool CreationOfNewGL {
        get {
            return this.creationOfNewGLField;
        }
        set {
            this.creationOfNewGLField = value;
        }
    }
    
    /// <remarks/>
    public Purpose Purpose {
        get {
            return this.purposeField;
        }
        set {
            this.purposeField = value;
        }
    }
    
    /// <remarks/>
    public LegislativeRequirements LegislativeRequirements {
        get {
            return this.legislativeRequirementsField;
        }
        set {
            this.legislativeRequirementsField = value;
        }
    }
    
    /// <remarks/>
    public Severity Severity {
        get {
            return this.severityField;
        }
        set {
            this.severityField = value;
        }
    }
    
    /// <remarks/>
    public GeneticStatus GeneticStatus {
        get {
            return this.geneticStatusField;
        }
        set {
            this.geneticStatusField = value;
        }
    }
    
    /// <remarks/>
    public Specie Species {
        get {
            return this.speciesField;
        }
        set {
            this.speciesField = value;
        }
    }
    
    /// <remarks/>
    public int ReportingYear {
        get {
            return this.reportingYearField;
        }
        set {
            this.reportingYearField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<NHPSource> NHPSource {
        get {
            return this.nHPSourceField;
        }
        set {
            this.nHPSourceField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<NHPGeneration> NHPGeneration {
        get {
            return this.nHPGenerationField;
        }
        set {
            this.nHPGenerationField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
    public System.Nullable<TestingByLegislation> TestingByLegislation {
        get {
            return this.testingByLegislationField;
        }
        set {
            this.testingByLegislationField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public partial class ApprovalUnitReportingLink {
    
    private System.Guid idField;
    
    private System.Guid approvalUnitIdField;
    
    private System.Guid reportingIdField;
    
    /// <remarks/>
    public System.Guid Id {
        get {
            return this.idField;
        }
        set {
            this.idField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid ApprovalUnitId {
        get {
            return this.approvalUnitIdField;
        }
        set {
            this.approvalUnitIdField = value;
        }
    }
    
    /// <remarks/>
    public System.Guid ReportingId {
        get {
            return this.reportingIdField;
        }
        set {
            this.reportingIdField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public enum PlaceOfBirth {
    
    /// <remarks/>
    O1,
    
    /// <remarks/>
    O2,
    
    /// <remarks/>
    O3,
    
    /// <remarks/>
    O4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public enum Purpose {
    
    /// <remarks/>
    PB1,
    
    /// <remarks/>
    PB2,
    
    /// <remarks/>
    PB3,
    
    /// <remarks/>
    PB4,
    
    /// <remarks/>
    PB5,
    
    /// <remarks/>
    PB6,
    
    /// <remarks/>
    PB7,
    
    /// <remarks/>
    PB8,
    
    /// <remarks/>
    PB9,
    
    /// <remarks/>
    PB10,
    
    /// <remarks/>
    PB11,
    
    /// <remarks/>
    PB12,
    
    /// <remarks/>
    PB13,
    
    /// <remarks/>
    PT21,
    
    /// <remarks/>
    PT22,
    
    /// <remarks/>
    PT23,
    
    /// <remarks/>
    PT24,
    
    /// <remarks/>
    PT25,
    
    /// <remarks/>
    PT26,
    
    /// <remarks/>
    PT27,
    
    /// <remarks/>
    PT28,
    
    /// <remarks/>
    PT29,
    
    /// <remarks/>
    PT30,
    
    /// <remarks/>
    PT31,
    
    /// <remarks/>
    PT32,
    
    /// <remarks/>
    PT33,
    
    /// <remarks/>
    PT34,
    
    /// <remarks/>
    PT35,
    
    /// <remarks/>
    PT36,
    
    /// <remarks/>
    PT37,
    
    /// <remarks/>
    PE40,
    
    /// <remarks/>
    PS41,
    
    /// <remarks/>
    PE42,
    
    /// <remarks/>
    PF43,
    
    /// <remarks/>
    PG43,
    
    /// <remarks/>
    PR51,
    
    /// <remarks/>
    PR52,
    
    /// <remarks/>
    PR53,
    
    /// <remarks/>
    PR61,
    
    /// <remarks/>
    PR62,
    
    /// <remarks/>
    PR63,
    
    /// <remarks/>
    PR64,
    
    /// <remarks/>
    PR71,
    
    /// <remarks/>
    PR81,
    
    /// <remarks/>
    PR82,
    
    /// <remarks/>
    PR83,
    
    /// <remarks/>
    PR84,
    
    /// <remarks/>
    PR85,
    
    /// <remarks/>
    PR86,
    
    /// <remarks/>
    PR87,
    
    /// <remarks/>
    PR88,
    
    /// <remarks/>
    PR89,
    
    /// <remarks/>
    PR90,
    
    /// <remarks/>
    PR91,
    
    /// <remarks/>
    PR92,
    
    /// <remarks/>
    PR93,
    
    /// <remarks/>
    PR94,
    
    /// <remarks/>
    PR95,
    
    /// <remarks/>
    PR96,
    
    /// <remarks/>
    PR97,
    
    /// <remarks/>
    PR98,
    
    /// <remarks/>
    PR99,
    
    /// <remarks/>
    PR100,
    
    /// <remarks/>
    PR101,
    
    /// <remarks/>
    PR102,
    
    /// <remarks/>
    PR103,
    
    /// <remarks/>
    PR104,
    
    /// <remarks/>
    PR105,
    
    /// <remarks/>
    PR106,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public enum LegislativeRequirements {
    
    /// <remarks/>
    LO1,
    
    /// <remarks/>
    LO2,
    
    /// <remarks/>
    LO3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public enum Severity {
    
    /// <remarks/>
    SV1,
    
    /// <remarks/>
    SV2,
    
    /// <remarks/>
    SV3,
    
    /// <remarks/>
    SV4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public enum GeneticStatus {
    
    /// <remarks/>
    GS1,
    
    /// <remarks/>
    GS2,
    
    /// <remarks/>
    GS3,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public enum Specie {
    
    /// <remarks/>
    A1,
    
    /// <remarks/>
    A2,
    
    /// <remarks/>
    A3,
    
    /// <remarks/>
    A4,
    
    /// <remarks/>
    A5,
    
    /// <remarks/>
    A6,
    
    /// <remarks/>
    A7,
    
    /// <remarks/>
    A8,
    
    /// <remarks/>
    A9,
    
    /// <remarks/>
    A10,
    
    /// <remarks/>
    A11,
    
    /// <remarks/>
    A12,
    
    /// <remarks/>
    A13,
    
    /// <remarks/>
    A14,
    
    /// <remarks/>
    A15,
    
    /// <remarks/>
    A16,
    
    /// <remarks/>
    A17,
    
    /// <remarks/>
    A18,
    
    /// <remarks/>
    A19,
    
    /// <remarks/>
    A20,
    
    /// <remarks/>
    A21,
    
    /// <remarks/>
    A22,
    
    /// <remarks/>
    A23,
    
    /// <remarks/>
    A24,
    
    /// <remarks/>
    A25,
    
    /// <remarks/>
    A26,
    
    /// <remarks/>
    A27,
    
    /// <remarks/>
    A28,
    
    /// <remarks/>
    A29,
    
    /// <remarks/>
    A30,
    
    /// <remarks/>
    A31,
    
    /// <remarks/>
    A32,
    
    /// <remarks/>
    A33,
    
    /// <remarks/>
    A34,
    
    /// <remarks/>
    A35,
    
    /// <remarks/>
    A36,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public enum NHPSource {
    
    /// <remarks/>
    NHPO1,
    
    /// <remarks/>
    NHPO2,
    
    /// <remarks/>
    NHPO3,
    
    /// <remarks/>
    NHPO4,
    
    /// <remarks/>
    NHPO5,
    
    /// <remarks/>
    NHPO6,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public enum NHPGeneration {
    
    /// <remarks/>
    NHPG1,
    
    /// <remarks/>
    NHPG2,
    
    /// <remarks/>
    NHPG3,
    
    /// <remarks/>
    NHPG4,
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://FVST.Dyreforsoeg.ReportingWebService/")]
public enum TestingByLegislation {
    
    /// <remarks/>
    LT1,
    
    /// <remarks/>
    LT2,
    
    /// <remarks/>
    LT3,
    
    /// <remarks/>
    LT4,
    
    /// <remarks/>
    LT5,
    
    /// <remarks/>
    LT6,
    
    /// <remarks/>
    LT7,
    
    /// <remarks/>
    LT8,
    
    /// <remarks/>
    LT9,
    
    /// <remarks/>
    LT10,
}
