//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AIRDsubmit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AIRDsubmit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A1] Mice (Mus musculus).
        /// </summary>
        internal static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A10] Dogs (Canis familiaris).
        /// </summary>
        internal static string A10 {
            get {
                return ResourceManager.GetString("A10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A11] Ferrets (Mustela putorius furo).
        /// </summary>
        internal static string A11 {
            get {
                return ResourceManager.GetString("A11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A12] Other carnivores (other Carnivora).
        /// </summary>
        internal static string A12 {
            get {
                return ResourceManager.GetString("A12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A13] Horses, donkeys and cross-breeds (Equidae).
        /// </summary>
        internal static string A13 {
            get {
                return ResourceManager.GetString("A13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A14] Pigs (Sus scrofa domesticus).
        /// </summary>
        internal static string A14 {
            get {
                return ResourceManager.GetString("A14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A15] Goats (Capra aegagrus hircus).
        /// </summary>
        internal static string A15 {
            get {
                return ResourceManager.GetString("A15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A16] Sheep (Ovis aries).
        /// </summary>
        internal static string A16 {
            get {
                return ResourceManager.GetString("A16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A17] Cattle (Bos primigenius).
        /// </summary>
        internal static string A17 {
            get {
                return ResourceManager.GetString("A17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A18] Prosimians (Prosimia).
        /// </summary>
        internal static string A18 {
            get {
                return ResourceManager.GetString("A18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A19] Marmoset and tamarins (eg. Callithrix jacchus).
        /// </summary>
        internal static string A19 {
            get {
                return ResourceManager.GetString("A19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A2] Rats (Rattus norvegicus).
        /// </summary>
        internal static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A20] Cynomolgus monkey (Macaca fascicularis).
        /// </summary>
        internal static string A20 {
            get {
                return ResourceManager.GetString("A20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A21] Rhesus monkey (Macaca mulatta).
        /// </summary>
        internal static string A21 {
            get {
                return ResourceManager.GetString("A21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A22] Vervets Chlorocebus spp. (usually either pygerythrus or sabaeus).
        /// </summary>
        internal static string A22 {
            get {
                return ResourceManager.GetString("A22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A23] Baboons (Papio spp.).
        /// </summary>
        internal static string A23 {
            get {
                return ResourceManager.GetString("A23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A24] Squirrel monkey (eg. Saimiri sciureus).
        /// </summary>
        internal static string A24 {
            get {
                return ResourceManager.GetString("A24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A25] Other species of non-human primates (other species of Ceboidea and Cercopithecoidea).
        /// </summary>
        internal static string A25 {
            get {
                return ResourceManager.GetString("A25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A26] Apes (Hominoidea).
        /// </summary>
        internal static string A26 {
            get {
                return ResourceManager.GetString("A26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A27] Other Mammals (other Mammalia).
        /// </summary>
        internal static string A27 {
            get {
                return ResourceManager.GetString("A27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A28] Domestic fowl (Gallus gallus domesticus).
        /// </summary>
        internal static string A28 {
            get {
                return ResourceManager.GetString("A28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A29] Other birds (other Aves).
        /// </summary>
        internal static string A29 {
            get {
                return ResourceManager.GetString("A29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A3] Guinea-Pigs (Cavia porcellus).
        /// </summary>
        internal static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A30] Reptiles (Reptilia).
        /// </summary>
        internal static string A30 {
            get {
                return ResourceManager.GetString("A30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A31] Rana (Rana temporaria and Rana pipiens).
        /// </summary>
        internal static string A31 {
            get {
                return ResourceManager.GetString("A31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A32] Xenopus (Xenopus laevis and Xenopus tropicalis).
        /// </summary>
        internal static string A32 {
            get {
                return ResourceManager.GetString("A32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A33] Other Amphibians (other Amphibia).
        /// </summary>
        internal static string A33 {
            get {
                return ResourceManager.GetString("A33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A34] Zebra fish (Danio rerio).
        /// </summary>
        internal static string A34 {
            get {
                return ResourceManager.GetString("A34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A35] Other Fish (other Pisces).
        /// </summary>
        internal static string A35 {
            get {
                return ResourceManager.GetString("A35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A36] Cephalopods (Cephalopoda).
        /// </summary>
        internal static string A36 {
            get {
                return ResourceManager.GetString("A36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A4] Hamsters (Syrian) (Mesocricetus auratus).
        /// </summary>
        internal static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A5] Hamsters (chinese) (Cricetulus griseus).
        /// </summary>
        internal static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A6] Mongolian gerbil (Meriones unguiculatus).
        /// </summary>
        internal static string A6 {
            get {
                return ResourceManager.GetString("A6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A7] Other Rodents (other Rodentia).
        /// </summary>
        internal static string A7 {
            get {
                return ResourceManager.GetString("A7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A8] Rabbits (Oryctolagus cuniculus).
        /// </summary>
        internal static string A8 {
            get {
                return ResourceManager.GetString("A8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [A9] Cats (Felis catus).
        /// </summary>
        internal static string A9 {
            get {
                return ResourceManager.GetString("A9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments 1.
        /// </summary>
        internal static string ColumnComments1 {
            get {
                return ResourceManager.GetString("ColumnComments1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments 2.
        /// </summary>
        internal static string ColumnComments2 {
            get {
                return ResourceManager.GetString("ColumnComments2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creation of Genetic Line.
        /// </summary>
        internal static string ColumnCreationOfGeneticLine {
            get {
                return ResourceManager.GetString("ColumnCreationOfGeneticLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom Severity.
        /// </summary>
        internal static string ColumnCustomSeverity {
            get {
                return ResourceManager.GetString("ColumnCustomSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genetic Status.
        /// </summary>
        internal static string ColumnGeneticStatus {
            get {
                return ResourceManager.GetString("ColumnGeneticStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legislative Requirement.
        /// </summary>
        internal static string ColumnLegislativeRequirements {
            get {
                return ResourceManager.GetString("ColumnLegislativeRequirements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHP Generation.
        /// </summary>
        internal static string ColumnNHPGeneration {
            get {
                return ResourceManager.GetString("ColumnNHPGeneration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NHP Source (origin).
        /// </summary>
        internal static string ColumnNHPSource {
            get {
                return ResourceManager.GetString("ColumnNHPSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of Animals.
        /// </summary>
        internal static string ColumnNumber {
            get {
                return ResourceManager.GetString("ColumnNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id 1.
        /// </summary>
        internal static string ColumnPermission {
            get {
                return ResourceManager.GetString("ColumnPermission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Place of birth (origin).
        /// </summary>
        internal static string ColumnPlaceOfBirth {
            get {
                return ResourceManager.GetString("ColumnPlaceOfBirth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Purpose.
        /// </summary>
        internal static string ColumnPurpose {
            get {
                return ResourceManager.GetString("ColumnPurpose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify Other (Purpose).
        /// </summary>
        internal static string ColumnPurposeOther {
            get {
                return ResourceManager.GetString("ColumnPurposeOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reuse.
        /// </summary>
        internal static string ColumnReuse {
            get {
                return ResourceManager.GetString("ColumnReuse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity.
        /// </summary>
        internal static string ColumnSeverity {
            get {
                return ResourceManager.GetString("ColumnSeverity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Animal Species.
        /// </summary>
        internal static string ColumnSpecies {
            get {
                return ResourceManager.GetString("ColumnSpecies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify other.
        /// </summary>
        internal static string ColumnSpeciesOther {
            get {
                return ResourceManager.GetString("ColumnSpeciesOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Testing by Legislation.
        /// </summary>
        internal static string ColumnTestingByLegislation {
            get {
                return ResourceManager.GetString("ColumnTestingByLegislation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specify other (Testing by Legislation).
        /// </summary>
        internal static string ColumnTestingByLegislationOther {
            get {
                return ResourceManager.GetString("ColumnTestingByLegislationOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded.
        /// </summary>
        internal static string ColumnUploaded {
            get {
                return ResourceManager.GetString("ColumnUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year.
        /// </summary>
        internal static string ColumnYear {
            get {
                return ResourceManager.GetString("ColumnYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2016.
        /// </summary>
        internal static string DefaultYear {
            get {
                return ResourceManager.GetString("DefaultYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GS1] Not genetically altered.
        /// </summary>
        internal static string GS1 {
            get {
                return ResourceManager.GetString("GS1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GS2] Genetically altered without a harmful phenotype.
        /// </summary>
        internal static string GS2 {
            get {
                return ResourceManager.GetString("GS2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [GS3] Genetically altered with a harmful phenotype.
        /// </summary>
        internal static string GS3 {
            get {
                return ResourceManager.GetString("GS3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LO1] Legislation satisfying EU requirements.
        /// </summary>
        internal static string LO1 {
            get {
                return ResourceManager.GetString("LO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LO2] Legislation satisfying national requirements only (within EU).
        /// </summary>
        internal static string LO2 {
            get {
                return ResourceManager.GetString("LO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LO3] Legislation satisfying Non-EU requirements only.
        /// </summary>
        internal static string LO3 {
            get {
                return ResourceManager.GetString("LO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LT1] Legislation on medicinal products for human use.
        /// </summary>
        internal static string LT1 {
            get {
                return ResourceManager.GetString("LT1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LT10] Other.
        /// </summary>
        internal static string LT10 {
            get {
                return ResourceManager.GetString("LT10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LT2] Legislation on medicinal products for veterinary use and their residues.
        /// </summary>
        internal static string LT2 {
            get {
                return ResourceManager.GetString("LT2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LT3] Medical devices legislation.
        /// </summary>
        internal static string LT3 {
            get {
                return ResourceManager.GetString("LT3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LT4] Industrial chemicals legislation.
        /// </summary>
        internal static string LT4 {
            get {
                return ResourceManager.GetString("LT4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LT5] Plant protection product legislation.
        /// </summary>
        internal static string LT5 {
            get {
                return ResourceManager.GetString("LT5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LT6] Biocides legislation.
        /// </summary>
        internal static string LT6 {
            get {
                return ResourceManager.GetString("LT6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LT7] Food legislation including food contact material.
        /// </summary>
        internal static string LT7 {
            get {
                return ResourceManager.GetString("LT7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LT8] Feed legislation including legislation for the safety of target animals, workers and environment.
        /// </summary>
        internal static string LT8 {
            get {
                return ResourceManager.GetString("LT8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [LT9] Cosmetics legislation.
        /// </summary>
        internal static string LT9 {
            get {
                return ResourceManager.GetString("LT9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NHPG1] F0.
        /// </summary>
        internal static string NHPG1 {
            get {
                return ResourceManager.GetString("NHPG1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NHPG2] F1.
        /// </summary>
        internal static string NHPG2 {
            get {
                return ResourceManager.GetString("NHPG2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NHPG3] F2 or greater.
        /// </summary>
        internal static string NHPG3 {
            get {
                return ResourceManager.GetString("NHPG3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NHPG4] Self-sustaining colony.
        /// </summary>
        internal static string NHPG4 {
            get {
                return ResourceManager.GetString("NHPG4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NHPO1] Animals born at a registered breeder within EU.
        /// </summary>
        internal static string NHPO1 {
            get {
                return ResourceManager.GetString("NHPO1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NHPO2] Animals born in rest of Europe.
        /// </summary>
        internal static string NHPO2 {
            get {
                return ResourceManager.GetString("NHPO2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NHPO3] Animals born in Asia.
        /// </summary>
        internal static string NHPO3 {
            get {
                return ResourceManager.GetString("NHPO3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NHPO4] Animals born in America.
        /// </summary>
        internal static string NHPO4 {
            get {
                return ResourceManager.GetString("NHPO4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NHPO5] Animals born in Africa.
        /// </summary>
        internal static string NHPO5 {
            get {
                return ResourceManager.GetString("NHPO5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [NHPO6] Animals born elsewhere.
        /// </summary>
        internal static string NHPO6 {
            get {
                return ResourceManager.GetString("NHPO6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [N] No.
        /// </summary>
        internal static string NO {
            get {
                return ResourceManager.GetString("NO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [O1] Animals born in the EU at a registered breeder.
        /// </summary>
        internal static string O1 {
            get {
                return ResourceManager.GetString("O1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [O2] Animals born in the EU but not at a registered breeder.
        /// </summary>
        internal static string O2 {
            get {
                return ResourceManager.GetString("O2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [O3] Animals born in rest of Europe.
        /// </summary>
        internal static string O3 {
            get {
                return ResourceManager.GetString("O3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [O4] Animals born in rest of world.
        /// </summary>
        internal static string O4 {
            get {
                return ResourceManager.GetString("O4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB1] (Basic Research) Oncology.
        /// </summary>
        internal static string PB1 {
            get {
                return ResourceManager.GetString("PB1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB10] (Basic Research) Endocrine System/Metabolism.
        /// </summary>
        internal static string PB10 {
            get {
                return ResourceManager.GetString("PB10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB11] (Basic Research) Multisystemic.
        /// </summary>
        internal static string PB11 {
            get {
                return ResourceManager.GetString("PB11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB12] (Basic Research) Ethology / Animal Behaviour /Animal Biology.
        /// </summary>
        internal static string PB12 {
            get {
                return ResourceManager.GetString("PB12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB13] (Basic Research) Other.
        /// </summary>
        internal static string PB13 {
            get {
                return ResourceManager.GetString("PB13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB2] (Basic Research) Cardiovascular Blood and Lymphatic System.
        /// </summary>
        internal static string PB2 {
            get {
                return ResourceManager.GetString("PB2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB3] (Basic Research) Nervous System.
        /// </summary>
        internal static string PB3 {
            get {
                return ResourceManager.GetString("PB3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB4] (Basic Research) Respiratory System.
        /// </summary>
        internal static string PB4 {
            get {
                return ResourceManager.GetString("PB4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB5] (Basic Research) Gastrointestinal System including Liver.
        /// </summary>
        internal static string PB5 {
            get {
                return ResourceManager.GetString("PB5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB6] (Basic Research) Musculoskeletal System.
        /// </summary>
        internal static string PB6 {
            get {
                return ResourceManager.GetString("PB6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB7] (Basic Research) Immune System.
        /// </summary>
        internal static string PB7 {
            get {
                return ResourceManager.GetString("PB7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB8] (Basic Research) Urogenital/Reproductive System.
        /// </summary>
        internal static string PB8 {
            get {
                return ResourceManager.GetString("PB8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PB9] (Basic Research) Sensory Organs (skin, eyes and ears).
        /// </summary>
        internal static string PB9 {
            get {
                return ResourceManager.GetString("PB9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PE40] Protection of the natural environment in the interests of the health or welfare of human beings or animals.
        /// </summary>
        internal static string PE40 {
            get {
                return ResourceManager.GetString("PE40", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PE42] Higher education or training for the acquisition, maintenance or improvement of vocational skills.
        /// </summary>
        internal static string PE42 {
            get {
                return ResourceManager.GetString("PE42", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PF43] Forensic enquiries.
        /// </summary>
        internal static string PF43 {
            get {
                return ResourceManager.GetString("PF43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PG43] Maintenance of colonies of established genetically altered animals, not used in other procedures.
        /// </summary>
        internal static string PG43 {
            get {
                return ResourceManager.GetString("PG43", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR100] (Regulatory use/Toxicity and../Ecotoxicity) Reproductive toxicity.
        /// </summary>
        internal static string PR100 {
            get {
                return ResourceManager.GetString("PR100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR101] (Regulatory use/Toxicity and../Ecotoxicity) Endocrine activity.
        /// </summary>
        internal static string PR101 {
            get {
                return ResourceManager.GetString("PR101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR102] (Regulatory use/Toxicity and.. /Ecotoxicity) Bioaccumulation.
        /// </summary>
        internal static string PR102 {
            get {
                return ResourceManager.GetString("PR102", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR103] (Regulatory use/Toxicity and.. /Ecotoxicity) Other.
        /// </summary>
        internal static string PR103 {
            get {
                return ResourceManager.GetString("PR103", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR104] (Regulatory use/Toxicity and..) Safety testing in food and feed area.
        /// </summary>
        internal static string PR104 {
            get {
                return ResourceManager.GetString("PR104", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR105] (Regulatory use/Toxicity and..) Target animal safety.
        /// </summary>
        internal static string PR105 {
            get {
                return ResourceManager.GetString("PR105", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR106] (Regulatory use/Toxicity and..) Other.
        /// </summary>
        internal static string PR106 {
            get {
                return ResourceManager.GetString("PR106", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR51] (Regulatory use/ Routine production) Blood based products.
        /// </summary>
        internal static string PR51 {
            get {
                return ResourceManager.GetString("PR51", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR52] (Regulatory use/ Routine production) Monoclonal antibodies.
        /// </summary>
        internal static string PR52 {
            get {
                return ResourceManager.GetString("PR52", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR53] (Regulatory use/ Routine production) Other.
        /// </summary>
        internal static string PR53 {
            get {
                return ResourceManager.GetString("PR53", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR61] (Regulatory use/ Quality control) Batch safety testing.
        /// </summary>
        internal static string PR61 {
            get {
                return ResourceManager.GetString("PR61", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR62] (Regulatory use/ Quality control) Pyrogenicity testing.
        /// </summary>
        internal static string PR62 {
            get {
                return ResourceManager.GetString("PR62", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR63] (Regulatory use/ Quality control) Batch potency testing.
        /// </summary>
        internal static string PR63 {
            get {
                return ResourceManager.GetString("PR63", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR64] (Regulatory use/Quality control) Other quality controls.
        /// </summary>
        internal static string PR64 {
            get {
                return ResourceManager.GetString("PR64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR71] (Regulatory use) Other efficacy and tolerance testing.
        /// </summary>
        internal static string PR71 {
            get {
                return ResourceManager.GetString("PR71", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR81] (Regulatory use/Toxicity and../Acute and sub-acute) LD50, LC50.
        /// </summary>
        internal static string PR81 {
            get {
                return ResourceManager.GetString("PR81", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR82] (Regulatory use/Toxicity and../Acute and sub-acute) Other lethal methods.
        /// </summary>
        internal static string PR82 {
            get {
                return ResourceManager.GetString("PR82", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR83] (Regulatory use/Toxicity and../Acute and sub-acute) Non lethal methods.
        /// </summary>
        internal static string PR83 {
            get {
                return ResourceManager.GetString("PR83", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR84] (Regulatory use/Toxicity and..) Skin irritation/corrosion.
        /// </summary>
        internal static string PR84 {
            get {
                return ResourceManager.GetString("PR84", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR85] (Regulatory use/Toxicity and..) Skin sensitisation.
        /// </summary>
        internal static string PR85 {
            get {
                return ResourceManager.GetString("PR85", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR86] (Regulatory use/Toxicity and..) Eye irritation/corrosion.
        /// </summary>
        internal static string PR86 {
            get {
                return ResourceManager.GetString("PR86", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR87] (Regulatory use/Toxicity and../Repeated dose toxicity) up to 28 days.
        /// </summary>
        internal static string PR87 {
            get {
                return ResourceManager.GetString("PR87", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR88] (Regulatory use/Toxicity and../Repeated dose toxicity) 29 - 90 days.
        /// </summary>
        internal static string PR88 {
            get {
                return ResourceManager.GetString("PR88", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR89] (Regulatory use/Toxicity and../Repeated dose toxicity) &gt; 90 days.
        /// </summary>
        internal static string PR89 {
            get {
                return ResourceManager.GetString("PR89", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR90] (Regulatory use/Toxicity and..) Carcinogenicity.
        /// </summary>
        internal static string PR90 {
            get {
                return ResourceManager.GetString("PR90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR91] (Regulatory use/Toxicity and..) Genotoxicity.
        /// </summary>
        internal static string PR91 {
            get {
                return ResourceManager.GetString("PR91", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR92] (Regulatory use/Toxicity and..) Reproductive toxicity.
        /// </summary>
        internal static string PR92 {
            get {
                return ResourceManager.GetString("PR92", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR93] (Regulatory use/Toxicity and..) Developmental toxicity.
        /// </summary>
        internal static string PR93 {
            get {
                return ResourceManager.GetString("PR93", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR94] (Regulatory use/Toxicity and..) Neurotoxicity.
        /// </summary>
        internal static string PR94 {
            get {
                return ResourceManager.GetString("PR94", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR95] (Regulatory use/Toxicity and..) Kinetics.
        /// </summary>
        internal static string PR95 {
            get {
                return ResourceManager.GetString("PR95", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR96] (Regulatory use/Toxicity and..) Pharmaco-dynamics (incl safety pharmacology).
        /// </summary>
        internal static string PR96 {
            get {
                return ResourceManager.GetString("PR96", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR97] (Regulatory use/Toxicity and..) Phototoxicity.
        /// </summary>
        internal static string PR97 {
            get {
                return ResourceManager.GetString("PR97", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR98] (Regulatory use/Toxicity and../Ecotoxicity) Acute toxicity.
        /// </summary>
        internal static string PR98 {
            get {
                return ResourceManager.GetString("PR98", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PR99] (Regulatory use/Toxicity and../Ecotoxicity) Chronic toxicity.
        /// </summary>
        internal static string PR99 {
            get {
                return ResourceManager.GetString("PR99", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PS41] Preservation of species.
        /// </summary>
        internal static string PS41 {
            get {
                return ResourceManager.GetString("PS41", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT21] (Trans/Appl Research) Human Cancer.
        /// </summary>
        internal static string PT21 {
            get {
                return ResourceManager.GetString("PT21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT22] (Trans/Appl Research) Human Infectious Disorders.
        /// </summary>
        internal static string PT22 {
            get {
                return ResourceManager.GetString("PT22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT23] (Trans/Appl Research) Human Cardiovascular Disorders.
        /// </summary>
        internal static string PT23 {
            get {
                return ResourceManager.GetString("PT23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT24] (Trans/Appl Research) Human Nervous and Mental Disorders.
        /// </summary>
        internal static string PT24 {
            get {
                return ResourceManager.GetString("PT24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT25] (Trans/Appl Research) Human Respiratory Disorders.
        /// </summary>
        internal static string PT25 {
            get {
                return ResourceManager.GetString("PT25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT26] (Trans/Appl Research) Human Gastrointestinal Disorders including Liver.
        /// </summary>
        internal static string PT26 {
            get {
                return ResourceManager.GetString("PT26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT27] (Trans/Appl Research) Human Musculoskeletal Disorders.
        /// </summary>
        internal static string PT27 {
            get {
                return ResourceManager.GetString("PT27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT28] (Trans/Appl Research) Human Immune Disorders.
        /// </summary>
        internal static string PT28 {
            get {
                return ResourceManager.GetString("PT28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT29] (Trans/Appl Research) Human Urogenital/Reproductive Disorders.
        /// </summary>
        internal static string PT29 {
            get {
                return ResourceManager.GetString("PT29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT30] (Trans/Appl Research) Human Sensory Organ Disorders (skin, eyes and ears).
        /// </summary>
        internal static string PT30 {
            get {
                return ResourceManager.GetString("PT30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT31] (Trans/Appl Research) Human Endocrine/Metabolism Disorders.
        /// </summary>
        internal static string PT31 {
            get {
                return ResourceManager.GetString("PT31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT32] (Trans/Appl Research) Other Human Disorders.
        /// </summary>
        internal static string PT32 {
            get {
                return ResourceManager.GetString("PT32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT33] (Trans/Appl Research) Animal Diseases and Disorders.
        /// </summary>
        internal static string PT33 {
            get {
                return ResourceManager.GetString("PT33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT34] (Trans/Appl Research) Animal Welfare.
        /// </summary>
        internal static string PT34 {
            get {
                return ResourceManager.GetString("PT34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT35] (Trans/Appl Research) Diagnosis of diseases.
        /// </summary>
        internal static string PT35 {
            get {
                return ResourceManager.GetString("PT35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT36] (Trans/Appl Research) Plant diseases.
        /// </summary>
        internal static string PT36 {
            get {
                return ResourceManager.GetString("PT36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [PT37] (Trans/Appl Research) Non-regulatory toxicology and ecotoxicology.
        /// </summary>
        internal static string PT37 {
            get {
                return ResourceManager.GetString("PT37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SV1] Non-recovery.
        /// </summary>
        internal static string SV1 {
            get {
                return ResourceManager.GetString("SV1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SV2] Mild (up to and including).
        /// </summary>
        internal static string SV2 {
            get {
                return ResourceManager.GetString("SV2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SV3] Moderate.
        /// </summary>
        internal static string SV3 {
            get {
                return ResourceManager.GetString("SV3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [SV4] Severe.
        /// </summary>
        internal static string SV4 {
            get {
                return ResourceManager.GetString("SV4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [Y] Yes.
        /// </summary>
        internal static string YES {
            get {
                return ResourceManager.GetString("YES", resourceCulture);
            }
        }
    }
}
